#############################################################################
# Makefile for building: GCS_for_UAV.app/Contents/MacOS/GCS_for_UAV
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  GCS_for_UAV.pro
# Template: app
# Command: /Users/jeongtaek/Qt/5.3/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile GCS_for_UAV.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_WEBKITWIDGETS_LIB -DQT_QUICK_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WEBKIT_LIB -DQT_QML_LIB -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_SENSORS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../../Qt/5.3/clang_64/mkspecs/macx-clang -I. -I../../../Qt/5.3/clang_64/lib/QtWebKitWidgets.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtQuick.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtMultimediaWidgets.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtOpenGL.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtWebKit.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtQml.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtMultimedia.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtNetwork.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtPositioning.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtSensors.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -F/Users/jeongtaek/Qt/5.3/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/jeongtaek/Qt/5.3/clang_64/lib -framework QtSerialPort -framework QtCore -framework QtWebKitWidgets -framework QtWebKit -framework QtNetwork -framework QtGui -framework QtWidgets -framework QtQuick -framework QtQml -framework QtMultimediaWidgets -framework QtMultimedia -framework QtOpenGL -framework QtPrintSupport -framework QtPositioning -framework QtSensors -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/jeongtaek/Qt/5.3/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		jtserialport.cpp \
		qcustomplot.cpp moc_mainwindow.cpp \
		moc_jtserialport.cpp \
		moc_qcustomplot.cpp
OBJECTS       = main.o \
		mainwindow.o \
		jtserialport.o \
		qcustomplot.o \
		moc_mainwindow.o \
		moc_jtserialport.o \
		moc_qcustomplot.o
DIST          = ../../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.3/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.3/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/lex.prf \
		GCS_for_UAV.pro main.cpp \
		mainwindow.cpp \
		jtserialport.cpp \
		qcustomplot.cpp
QMAKE_TARGET  = GCS_for_UAV
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = GCS_for_UAV.app/Contents/MacOS/GCS_for_UAV

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile GCS_for_UAV.app/Contents/PkgInfo GCS_for_UAV.app/Contents/Resources/empty.lproj GCS_for_UAV.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d GCS_for_UAV.app/Contents/MacOS/ || mkdir -p GCS_for_UAV.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GCS_for_UAV.pro ../../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.3/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.3/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.3/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.3/clang_64/mkspecs/features/lex.prf \
		GCS_for_UAV.pro \
		/Users/jeongtaek/Qt/5.3/clang_64/lib/QtSerialPort.framework/QtSerialPort.prl \
		/Users/jeongtaek/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/jeongtaek/Qt/5.3/clang_64/lib/QtWebKitWidgets.framework/QtWebKitWidgets.prl \
		/Users/jeongtaek/Qt/5.3/clang_64/lib/QtWebKit.framework/QtWebKit.prl \
		/Users/jeongtaek/Qt/5.3/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/jeongtaek/Qt/5.3/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/jeongtaek/Qt/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/jeongtaek/Qt/5.3/clang_64/lib/QtQuick.framework/QtQuick.prl \
		/Users/jeongtaek/Qt/5.3/clang_64/lib/QtQml.framework/QtQml.prl \
		/Users/jeongtaek/Qt/5.3/clang_64/lib/QtMultimediaWidgets.framework/QtMultimediaWidgets.prl \
		/Users/jeongtaek/Qt/5.3/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl \
		/Users/jeongtaek/Qt/5.3/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Users/jeongtaek/Qt/5.3/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl \
		/Users/jeongtaek/Qt/5.3/clang_64/lib/QtPositioning.framework/QtPositioning.prl \
		/Users/jeongtaek/Qt/5.3/clang_64/lib/QtSensors.framework/QtSensors.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile GCS_for_UAV.pro
../../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.3/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.3/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf:
../../../Qt/5.3/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.3/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.3/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.3/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.3/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.3/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf:
../../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.3/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.3/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.3/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.3/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.3/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.3/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.3/clang_64/mkspecs/features/lex.prf:
GCS_for_UAV.pro:
/Users/jeongtaek/Qt/5.3/clang_64/lib/QtSerialPort.framework/QtSerialPort.prl:
/Users/jeongtaek/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/jeongtaek/Qt/5.3/clang_64/lib/QtWebKitWidgets.framework/QtWebKitWidgets.prl:
/Users/jeongtaek/Qt/5.3/clang_64/lib/QtWebKit.framework/QtWebKit.prl:
/Users/jeongtaek/Qt/5.3/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Users/jeongtaek/Qt/5.3/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/jeongtaek/Qt/5.3/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/jeongtaek/Qt/5.3/clang_64/lib/QtQuick.framework/QtQuick.prl:
/Users/jeongtaek/Qt/5.3/clang_64/lib/QtQml.framework/QtQml.prl:
/Users/jeongtaek/Qt/5.3/clang_64/lib/QtMultimediaWidgets.framework/QtMultimediaWidgets.prl:
/Users/jeongtaek/Qt/5.3/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl:
/Users/jeongtaek/Qt/5.3/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
/Users/jeongtaek/Qt/5.3/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl:
/Users/jeongtaek/Qt/5.3/clang_64/lib/QtPositioning.framework/QtPositioning.prl:
/Users/jeongtaek/Qt/5.3/clang_64/lib/QtSensors.framework/QtSensors.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile GCS_for_UAV.pro

qmake_all: FORCE

GCS_for_UAV.app/Contents/PkgInfo: 
	@test -d GCS_for_UAV.app/Contents || mkdir -p GCS_for_UAV.app/Contents
	@$(DEL_FILE) GCS_for_UAV.app/Contents/PkgInfo
	@echo "APPL????" >GCS_for_UAV.app/Contents/PkgInfo
GCS_for_UAV.app/Contents/Resources/empty.lproj: 
	@test -d GCS_for_UAV.app/Contents/Resources || mkdir -p GCS_for_UAV.app/Contents/Resources
	@touch GCS_for_UAV.app/Contents/Resources/empty.lproj
	
GCS_for_UAV.app/Contents/Info.plist: 
	@test -d GCS_for_UAV.app/Contents || mkdir -p GCS_for_UAV.app/Contents
	@$(DEL_FILE) GCS_for_UAV.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@BUNDLEIDENTIFIER@,JT.GCS_for_UAV,g" -e "s,@EXECUTABLE@,GCS_for_UAV,g" -e "s,@TYPEINFO@,????,g" ../../../Qt/5.3/clang_64/mkspecs/macx-clang/Info.plist.app >GCS_for_UAV.app/Contents/Info.plist
dist: 
	@test -d .tmp/GCS_for_UAV1.0.0 || mkdir -p .tmp/GCS_for_UAV1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/GCS_for_UAV1.0.0/ && $(COPY_FILE) --parents mainwindow.h jtserialport.h qcustomplot.h .tmp/GCS_for_UAV1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp jtserialport.cpp qcustomplot.cpp .tmp/GCS_for_UAV1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/GCS_for_UAV1.0.0/ && (cd `dirname .tmp/GCS_for_UAV1.0.0` && $(TAR) GCS_for_UAV1.0.0.tar GCS_for_UAV1.0.0 && $(COMPRESS) GCS_for_UAV1.0.0.tar) && $(MOVE) `dirname .tmp/GCS_for_UAV1.0.0`/GCS_for_UAV1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/GCS_for_UAV1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r GCS_for_UAV.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_jtserialport.cpp moc_qcustomplot.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_jtserialport.cpp moc_qcustomplot.cpp
moc_mainwindow.cpp: ../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		mainwindow.h
	/Users/jeongtaek/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/jeongtaek/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/jeongtaek/Dropbox/Development/GCS_for_UAV -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtWebKitWidgets.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtQuick.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtMultimediaWidgets.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtOpenGL.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtWebKit.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtQml.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtMultimedia.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtPositioning.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtSensors.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/jeongtaek/Qt/5.3/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_jtserialport.cpp: ../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		jtserialport.h
	/Users/jeongtaek/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/jeongtaek/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/jeongtaek/Dropbox/Development/GCS_for_UAV -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtWebKitWidgets.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtQuick.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtMultimediaWidgets.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtOpenGL.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtWebKit.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtQml.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtMultimedia.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtPositioning.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtSensors.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/jeongtaek/Qt/5.3/clang_64/lib jtserialport.h -o moc_jtserialport.cpp

moc_qcustomplot.cpp: mainwindow.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QPointer \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qpointer.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPainter \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPaintEvent \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPixmap \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmap.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QMultiMap \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qmap.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QFlags \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qflags.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QVector2D \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector2d.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QStack \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstack.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QCache \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QMargins \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qmargins.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qmath.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qnumeric.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/QPrinter \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprinter.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/QPrintEngine \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprintengine.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtNumeric \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/QtPrintSupport \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qabstractprintdialog.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qpagesetupdialog.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprintdialog.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprintpreviewdialog.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprinterinfo.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qtprintsupportglobal.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprintpreviewwidget.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qtprintsupportversion.h \
		qcustomplot.h
	/Users/jeongtaek/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/jeongtaek/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/jeongtaek/Dropbox/Development/GCS_for_UAV -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtWebKitWidgets.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtQuick.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtMultimediaWidgets.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtOpenGL.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtPrintSupport.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtWebKit.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtQml.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtMultimedia.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtWidgets.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtNetwork.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtPositioning.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtSensors.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/jeongtaek/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/jeongtaek/Qt/5.3/clang_64/lib qcustomplot.h -o moc_qcustomplot.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		qcustomplot.h \
		mainwindow.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QPointer \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qpointer.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPainter \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPaintEvent \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPixmap \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmap.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QMultiMap \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qmap.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QFlags \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qflags.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QVector2D \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector2d.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QStack \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstack.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QCache \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QMargins \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qmargins.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qmath.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qnumeric.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/QPrinter \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprinter.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/QPrintEngine \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprintengine.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtNumeric \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/QtPrintSupport \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qabstractprintdialog.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qpagesetupdialog.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprintdialog.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprintpreviewdialog.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprinterinfo.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qtprintsupportglobal.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprintpreviewwidget.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qtprintsupportversion.h
	/Users/jeongtaek/Qt/5.3/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		jtserialport.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QPushButton \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qpushbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		ui_mainwindow.h \
		qcustomplot.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QPointer \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qpointer.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPainter \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPaintEvent \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPixmap \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmap.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QMultiMap \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qmap.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QFlags \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qflags.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QVector2D \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector2d.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QStack \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstack.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QCache \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QMargins \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qmargins.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qmath.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qnumeric.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/QPrinter \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprinter.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/QPrintEngine \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprintengine.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtNumeric \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/QtPrintSupport \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qabstractprintdialog.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qpagesetupdialog.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprintdialog.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprintpreviewdialog.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprinterinfo.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qtprintsupportglobal.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprintpreviewwidget.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qtprintsupportversion.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QUrl \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qurl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

jtserialport.o: jtserialport.cpp jtserialport.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jtserialport.o jtserialport.cpp

qcustomplot.o: qcustomplot.cpp qcustomplot.h \
		mainwindow.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QPointer \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qpointer.h \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../../Qt/5.3/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPainter \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPaintEvent \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QPixmap \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmap.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QMultiMap \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qmap.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QFlags \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qflags.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QVector2D \
		../../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector2d.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QStack \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qstack.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QCache \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QMargins \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qmargins.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qmath.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qnumeric.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/QPrinter \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprinter.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/QPrintEngine \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprintengine.h \
		../../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QtNumeric \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/QtPrintSupport \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qabstractprintdialog.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qpagesetupdialog.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprintdialog.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprintpreviewdialog.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprinterinfo.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qtprintsupportglobal.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qprintpreviewwidget.h \
		../../../Qt/5.3/clang_64/lib/QtPrintSupport.framework/Versions/5/Headers/qtprintsupportversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomplot.o qcustomplot.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_jtserialport.o: moc_jtserialport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_jtserialport.o moc_jtserialport.cpp

moc_qcustomplot.o: moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomplot.o moc_qcustomplot.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

